### ISSUE TITLE
课堂点名应用

### ISSUE THREAD

**Issue by meflyup** [ECNU-DEIT-2015/exercise#1]
如果要做一个课堂点名的应用，请你思考：
- 有哪些需求
- 涉及到哪些技术
- 你的方案是什么

**Comment by 10154507121** [comment]
每个同学被点到名的可能性相等
重复随机点名，如果一个人被点到一次，他就应该在下次随机范围之外

**Comment by JasmineSSSong** [comment]
#需求
点名结果可以自动生成文件上传到数据库进行统计
防止代替签到

**Comment by 10154507127** [comment]
#需求
* 随机抽取
* 抽取一定数量的学生
* 打标签，区分学生是否到场
* 记数，某学生被抽到几次，到场次数，缺勤次数

**Comment by Lethemay** [comment]
1. 应用程序根据名单随机生成点名的人
2. 每个人被点到的概率应该相等

**Comment by LemonCui** [comment]
不能有人代替签到

**Comment by 10154507102xiehanhan** [comment]
不能漏掉点名
存在一定顺序
根据不同的班级需求可以自适应的点名顺序

**Comment by JzyTvT** [comment]
之前被点到同学，下次被点到的几率变小，没有被点到的同学被点到的几率变大

**Comment by Celiare** [comment]
#### 1. 每个人被点到的概率相等
#### 2. 记录点名情况，回答问题情况

**Comment by 10154507134** [comment]
需求：
含有学生姓名、学生学号，课程名称的数据库表；（课程名称主键）
含有账号、密码、课程名称的数据库表。（账号主键，课程名称外键）
随机点名。

技术：
数据库与前端界面交互技术；
随机数算法技术；

方案：
登录系统后，从后台数据库中进行账号密码验证，根据课程名称调出课程名单。
使用随机数算法，对名单中所有人进行随机点名。（比如有50人，则写一个1-50随机数算法，对应每位学生，点到几，则哪个学生被点到名。）

**Comment by XieQi-2017** [comment]
1、可以分为小组等方式进行点名，确保每个同学均点到；
2、每个学生记录个人出勤情况，设置相关参数；
3、教师数据分类明确。点过谁，下次推荐谁

**Comment by ZhangSining** [comment]
1.课前签到，课上不会点到缺课的人；
2.每个人被点到几率相等；
3.记录每次点名的结果

**Comment by HanQingHuI** [comment]
## 需求
#### 点名必须随机
#### 区分同名同姓之人
#### 点名范围规定好
#### 点名必须可以认为控制次数
#### 每次点名必须初始化
#### 点过之人必须标注
#### 可以选择一次可以点几个人

**Comment by Yuxiaoxue2015** [comment]
1、需求：
a.随机性:每个同学被点到的可能性是相同的
b.缩短点名时间，每次抽取学生的数目可调整
c.保存每位学生的点名记录

2、技术：
a.建立学生姓名、学号、年级、系所等基本信息数据库以及个人账号密码身份数据库
b.后台数据库与前端的连接
c.前端的交互设计

3、方案：
a.给分配身份：教师、学生
b.注册登录：建立个人用户名与密码的数据库
c.教师身份：抽取一定数量的学生点名、查看点名情况、管理学生信息
d.学生身份：查看个人点名情况

**Comment by Lethemay** [comment]
完成点名后，可以将点名结果输出到文本文件中

**Comment by 10154507117** [comment]
有哪些需求：
1.包括本次课堂的授课老师和参与该课堂的学生人数和具体名单；
2.要确保学生确实到达现场，而非在任何地点只要知道相关信息就能完成签到
3.合理、可靠的点名机制
涉及到的技术：GPS定位……
方案：基于GPS，获取学生的地理位置，根据学生的地理位置与教室位置进行比较……

**Comment by guanqunliu** [comment]
课上一直刷不开这个网站~现在补充几句~
**需求：**
①成员管理
②课程管理
③签到
④班级平均出勤次数
⑤出勤率（可用图表表示）
⑥随机点名

**设计到的技术：**
数据库，数据库连接、统计的相关算法、记录、允许并发操作

**方案：**
①首先能实现一个人打卡签到
②允许多位学生同时进行签到
③分班级管理
④分课程管理
⑤统计数据应用
